### ISSUE TITLE
Customer seeing executor shutdown error in HelloSignalTest

### ISSUE THREAD

**Issue by wxing1292** [uber/cadence-java-client#241]
the stack trace:

```
java.util.concurrent.RejectedExecutionException: Executor is shutdown
    at com.uber.cadence.internal.worker.BlockCallerPolicy.rejectedExecution(BlockCallerPolicy.java:30)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
    at com.uber.cadence.internal.worker.PollTaskExecutor.process(PollTaskExecutor.java:66)
    at com.uber.cadence.internal.worker.Poller$PollExecutionTask.run(Poller.java:256)
    at com.uber.cadence.internal.worker.Poller$PollLoopTask.run(Poller.java:223)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by shail** [comment]
I was actually able to figure out the issue. The activity & workflow RetryOptions were misconfigured, causing a timeout issue which was getting swallowed by the global test timeout that was being set. Once I removed the global test timeout, I was able to see the proper error message and move past it.

**Comment by mfateev** [comment]
Nice, resolving.
