### ISSUE TITLE
EntityNotExists activity completion error is retried

### ISSUE THREAD

**Issue by mfateev** [uber/cadence-java-client#247]
When using Java Client, have been seeing burst of "Retrying after failure" error some time. LIke this one https://search.uberinternal.com/#dashboard/temp/AWhdHrRwmJs65Bl-eJs8
c.u.c.EntityNotExistsError: Workflow execution already completed.
    at c.u.c.WorkflowService$RespondActivityTaskCompleted_result$RespondActivityTaskCompleted_resultStandardScheme.read(WorkflowService.java:23722)
    at c.u.c.WorkflowService$RespondActivityTaskCompleted_result$RespondActivityTaskCompleted_resultStandardScheme.read(WorkflowService.java:23690)
    at c.u.c.WorkflowService$RespondActivityTaskCompleted_result.read(WorkflowService.java:23600)
    at o.apache.thrift.TDeserializer.deserialize(TDeserializer.java:81)
    at o.apache.thrift.TDeserializer.deserialize(TDeserializer.java:67)
    at c.u.t.m.ThriftSerializer.decodeBody(ThriftSerializer.java:70)
    at c.u.t.messages.Serializer.decodeBody(Serializer.java:49)
    at c.u.t.messages.EncodedResponse.getBody(EncodedResponse.java:85)
    at c.u.c.s.WorkflowServiceTChannel.respondActivityTaskCompleted(WorkflowServiceTChannel.java:1121)
    at c.u.c.s.WorkflowServiceTChannel.lambda$RespondActivityTaskCompleted$15(WorkflowServiceTChannel.java:1108)
    at c.u.c.s.WorkflowServiceTChannel.lambda$measureRemoteProc$1(WorkflowServiceTChannel.java:518)
    at c.u.c.s.WorkflowServiceTChannel.measureRemoteCall(WorkflowServiceTChannel.java:492)
    at c.u.c.s.WorkflowServiceTChannel.measureRemoteProc(WorkflowServiceTChannel.java:515)
    at c.u.c.s.WorkflowServiceTChannel.RespondActivityTaskCompleted(WorkflowServiceTChannel.java:1107)
    at c.u.c.i.w.ActivityWorker$TaskHandlerImpl.lambda$sendReply$0(ActivityWorker.java:230)
    at c.u.c.internal.common.Retryer.lambda$retry$0(Retryer.java:75)
    at c.u.c.internal.common.Retryer.retryWithResult(Retryer.java:93)
    at c.u.c.internal.common.Retryer.retry(Retryer.java:72)
    at c.u.c.i.w.ActivityWorker$TaskHandlerImpl.sendReply(ActivityWorker.java:230)
    at c.u.c.i.w.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:187)
    at c.u.c.i.w.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:158)
    at c.u.c.i.w.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:71)
    at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by mfateev** [comment]
The same problem with decision completion:

c.u.c.EntityNotExistsError: Decision task not found.
    at c.u.c.WorkflowService$RespondDecisionTaskCompleted_result$RespondDecisionTaskCompleted_resultStandardScheme.read(WorkflowService.java:17056)
    at c.u.c.WorkflowService$RespondDecisionTaskCompleted_result$RespondDecisionTaskCompleted_resultStandardScheme.read(WorkflowService.java:17015)
    at c.u.c.WorkflowService$RespondDecisionTaskCompleted_result.read(WorkflowService.java:16914)
    at o.apache.thrift.TDeserializer.deserialize(TDeserializer.java:81)
    at o.apache.thrift.TDeserializer.deserialize(TDeserializer.java:67)
    at c.u.t.m.ThriftSerializer.decodeBody(ThriftSerializer.java:70)
    at c.u.t.messages.Serializer.decodeBody(Serializer.java:49)
    at c.u.t.messages.EncodedResponse.getBody(EncodedResponse.java:85)
    at c.u.c.s.WorkflowServiceTChannel.respondDecisionTaskCompleted(WorkflowServiceTChannel.java:879)
    at c.u.c.s.WorkflowServiceTChannel.lambda$RespondDecisionTaskCompleted$10(WorkflowServiceTChannel.java:865)
    at c.u.c.s.WorkflowServiceTChannel.measureRemoteCall(WorkflowServiceTChannel.java:492)
    at c.u.c.s.WorkflowServiceTChannel.RespondDecisionTaskCompleted(WorkflowServiceTChannel.java:863)
    at c.u.c.i.w.WorkflowWorker$TaskHandlerImpl.lambda$sendReply$0(WorkflowWorker.java:273)
    at c.u.c.internal.common.Retryer.lambda$retry$0(Retryer.java:75)
    at c.u.c.internal.common.Retryer.retryWithResult(Retryer.java:93)
    at c.u.c.internal.common.Retryer.retry(Retryer.java:72)
    at c.u.c.i.w.WorkflowWorker$TaskHandlerImpl.sendReply(WorkflowWorker.java:273)
    at c.u.c.i.w.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:242)
    at c.u.c.i.w.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:221)
    at c.u.c.i.w.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:71)
    at j.u.c.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at j.u.c.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

**Comment by meiliang86** [comment]
This is already fixed in the latest version.
Based on the stack trace you were using an old version of the library that does not have the fix.
