### ISSUE TITLE
StartWorkflowExecution failed with unknown error 

### ISSUE THREAD

**Issue by satb** [uber/cadence-java-client#251]
I am trying a very simple example of the file download as shown in the readme file. I ran the docker-compose up and everything seems fine. However, when I launch the workflow, two things happen

1. It hangs forever 2. I get the following stack dump

```
Exception in thread "main" com.uber.cadence.client.WorkflowServiceException: WorkflowType="FileProcessingWorkflow::processFile
	at com.uber.cadence.internal.sync.WorkflowStubImpl.startWithOptions(WorkflowStubImpl.java:134)
	at com.uber.cadence.internal.sync.WorkflowStubImpl.start(WorkflowStubImpl.java:144)
	at com.uber.cadence.internal.sync.WorkflowInvocationHandler.startWorkflow(WorkflowInvocationHandler.java:211)
	at com.uber.cadence.internal.sync.WorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:169)
	at com.sun.proxy.$Proxy4.processFile(Unknown Source)
	at com.cadencetest.Application.main(Application.java:9)
Caused by: org.apache.thrift.TException: StartWorkflowExecution failed with unknown error:StartWorkflowExecution_result(success:null, badRequestError:null, internalServiceError:null, sessionAlreadyExistError:null, serviceBusyError:null)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.startWorkflowExecution(WorkflowServiceTChannel.java:646)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.lambda$StartWorkflowExecution$6(WorkflowServiceTChannel.java:616)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.measureRemoteCall(WorkflowServiceTChannel.java:444)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.StartWorkflowExecution(WorkflowServiceTChannel.java:615)
	at com.uber.cadence.internal.external.GenericWorkflowClientExternalImpl.startWorkflowInternal(GenericWorkflowClientExternalImpl.java:116)
	at com.uber.cadence.internal.external.GenericWorkflowClientExternalImpl.startWorkflow(GenericWorkflowClientExternalImpl.java:74)
	at com.uber.cadence.internal.sync.WorkflowStubImpl.startWithOptions(WorkflowStubImpl.java:126)
	... 5 more
```

POM has the following:

```
<dependency>
            <groupId>com.uber.cadence</groupId>
            <artifactId>cadence-client</artifactId>
            <version>2.0.0</version>
</dependency>
```

Application.java has a simple main method that does this

```
public class Application {

    public static void main(String[] args) {

        WorkflowClient workflowClient = WorkflowClient.newInstance("127.0.0.1", 7933, "cadencetest");
        FileProcessingWorkflow fileProcessingWorkflow = workflowClient.newWorkflowStub(FileProcessingWorkflow.class);

        String result = fileProcessingWorkflow.processFile(args);

        System.out.println("Done! " + result);
    }
}
```

Running the main method results in the stack trace. 

Could you please give me some pointers where to look?

I tried running everything outside docker as well. I get the following error (slightly different)

```
Exception in thread "main" com.uber.cadence.client.WorkflowServiceException: WorkflowType="FileProcessingWorkflow::processFile
	at com.uber.cadence.internal.sync.WorkflowStubImpl.startWithOptions(WorkflowStubImpl.java:134)
	at com.uber.cadence.internal.sync.WorkflowStubImpl.start(WorkflowStubImpl.java:144)
	at com.uber.cadence.internal.sync.WorkflowInvocationHandler.startWorkflow(WorkflowInvocationHandler.java:211)
	at com.uber.cadence.internal.sync.WorkflowInvocationHandler.invoke(WorkflowInvocationHandler.java:169)
	at com.sun.proxy.$Proxy4.processFile(Unknown Source)
	at com.cadencetest.Application.main(Application.java:9)
Caused by: org.apache.thrift.TException: Rpc error:<ErrorResponse id=1 errorType=BadRequest message=no handler for service "cadence-frontend" and method "WorkflowService::StartWorkflowExecution">
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.throwOnRpcError(WorkflowServiceTChannel.java:425)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.doRemoteCall(WorkflowServiceTChannel.java:400)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.startWorkflowExecution(WorkflowServiceTChannel.java:628)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.lambda$StartWorkflowExecution$6(WorkflowServiceTChannel.java:616)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.measureRemoteCall(WorkflowServiceTChannel.java:444)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.StartWorkflowExecution(WorkflowServiceTChannel.java:615)
	at com.uber.cadence.internal.external.GenericWorkflowClientExternalImpl.startWorkflowInternal(GenericWorkflowClientExternalImpl.java:116)
	at com.uber.cadence.internal.external.GenericWorkflowClientExternalImpl.startWorkflow(GenericWorkflowClientExternalImpl.java:74)
	at com.uber.cadence.internal.sync.WorkflowStubImpl.startWithOptions(WorkflowStubImpl.java:126)

```

So, I ran the cadence-java-samples HelloActivity. The error is different again. Why doesn't the main method ever return? It just hangs there. Is that expected?

```

com.uber.cadence.EntityNotExistsError: Domain sample does not exist.
	at com.uber.cadence.WorkflowService$PollForActivityTask_result$PollForActivityTask_resultStandardScheme.read(WorkflowService.java:19712)
	at com.uber.cadence.WorkflowService$PollForActivityTask_result$PollForActivityTask_resultStandardScheme.read(WorkflowService.java:19653)
	at com.uber.cadence.WorkflowService$PollForActivityTask_result.read(WorkflowService.java:19552)
	at org.apache.thrift.TDeserializer.deserialize(TDeserializer.java:81)
	at org.apache.thrift.TDeserializer.deserialize(TDeserializer.java:67)
	at com.uber.tchannel.messages.ThriftSerializer.decodeBody(ThriftSerializer.java:72)
	at com.uber.tchannel.messages.Serializer.decodeBody(Serializer.java:49)
	at com.uber.tchannel.messages.EncodedResponse.getBody(EncodedResponse.java:85)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.pollForActivityTask(WorkflowServiceTChannel.java:977)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.lambda$PollForActivityTask$12(WorkflowServiceTChannel.java:963)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.measureRemoteCall(WorkflowServiceTChannel.java:492)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.PollForActivityTask(WorkflowServiceTChannel.java:962)
	at com.uber.cadence.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:64)
	at com.uber.cadence.internal.worker.ActivityPollTask.poll(ActivityPollTask.java:32)
	at com.uber.cadence.internal.worker.Poller$PollExecutionTask.run(Poller.java:252)
	at com.uber.cadence.internal.worker.Poller$PollLoopTask.run(Poller.java:223)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

```

**Comment by satb** [comment]
OK. To see why the HelloActivity is not running, I looked into cassandra's cadence keyspace, I see there is a domains table. Inspecting that table I see this

```
cqlsh:cadence> select * from domains;

 id                                   | config | domain
--------------------------------------+--------+----------------------------------------------------------------------------------------------------
 32049b68-7872-4094-8e63-d0dd59896a83 |   null | {id: null, name: 'cadence-system', status: null, description: null, owner_email: null, data: null}
```

I am assuming "make install-schema" put the domain there. However, it put the domain as "cadence-system". So, I went to the java-samples again, and changed the "DOMAIN" value in the SampleConstants file to "cadence-system" and lo and behold, the HelloActivity runs. 

Do we have to manually insert the domain if we want to use a different one?

**Comment by dmetzgar** [comment]
The cadence-system domain is for a different purpose. You can create the samples domain with the instructions from our sample repo [here](https://github.com/uber/cadence-java-samples#register-the-domain).

**Comment by mfateev** [comment]
The cadence-java-samples contain [RegisterDomain](https://github.com/uber/cadence-java-samples/blob/master/src/main/java/com/uber/cadence/samples/common/RegisterDomain.java) helper class that can be used to register the domain.

**Comment by mfateev** [comment]
And cadence-java-samples [README](https://github.com/uber/cadence-java-samples) mentions domain registration.

**Comment by mfateev** [comment]
Resolving. Reopen is it is still an issue.
