### ISSUE TITLE
Failed to run Hello example - IllegalAccessException

### ISSUE THREAD

**Issue by tuan-nng** [uber/cadence-java-client#489]
I tried to run the hello example at https://cadenceworkflow.io/docs/06_javaclient/01_quick_start

However, I got the error when starting the workflow

```
20:48:54.846 [Workflow Executor taskList="HelloWorldTaskList", domain="test-domain": 1] ERROR c.u.c.internal.worker.PollerOptions - uncaught exception
java.lang.RuntimeException: Failure processing decision task. WorkflowID=7a25133d-ae65-4180-8fa3-86e340662b3f, RunID=31968a6e-1027-4b3b-9194-3c8536f47783
        at com.uber.cadence.internal.worker.WorkflowWorker$TaskHandlerImpl.wrapFailure(WorkflowWorker.java:283)
        at com.uber.cadence.internal.worker.WorkflowWorker$TaskHandlerImpl.wrapFailure(WorkflowWorker.java:229)
        at com.uber.cadence.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:76)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Error: com.uber.cadence.internal.worker.WorkflowExecutionException: java.lang.IllegalAccessException
        at com.uber.cadence.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:250)
        at com.uber.cadence.internal.sync.WorkflowRunnable.run(WorkflowRunnable.java:47)
        at com.uber.cadence.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102)
        at com.uber.cadence.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:99)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 common frames omitted
Caused by: com.uber.cadence.internal.worker.WorkflowExecutionException: java.lang.IllegalAccessException
        at com.uber.cadence.internal.sync.POJOWorkflowImplementationFactory.mapToWorkflowExecutionException(POJOWorkflowImplementationFactory.java:367)
        ... 9 common frames omitted

```

Can someone have a look?

**Comment by seonwuka** [comment]
Same issue here, did you get a solution yet?

**Comment by seonwuka** [comment]
make the interface public
