### ISSUE TITLE
Flaky test ReplayDeciderCacheTests.whenHistoryIsPartialCachedEntryIsReturned

### ISSUE THREAD

**Issue by vancexu** [uber/cadence-java-client#502]
```
Argument(s) are different! Wanted:
statsReporter.reportCounter(
    "cadence-sticky-cache-hit",
    {Domain=domain, TaskList=stickyTaskList},
    1
);
-> at com.uber.cadence.internal.replay.ReplayDeciderCacheTests.whenHistoryIsPartialCachedEntryIsReturned(ReplayDeciderCacheTests.java:139)
Actual invocation has different arguments:
statsReporter.reportCounter(
    "cadence-sticky-cache-total-forced-eviction",
    {Domain=domain, TaskList=stickyTaskList},
    1
);
-> at com.uber.m3.tally.CounterImpl.report(CounterImpl.java:59)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.uber.cadence.internal.replay.ReplayDeciderCacheTests.whenHistoryIsPartialCachedEntryIsReturned(ReplayDeciderCacheTests.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vancexu** [comment]
too old, closed.
