### ISSUE TITLE
Timeout exception in log when use a server on K8 hosted on AWS EKS

### ISSUE THREAD

**Issue by sunshineo** [uber/cadence-java-client#505]
I followed the tutorial and got everything working locally. Then I start to move things onto company's Kubernetes hosted on AWS EKS.

My service seems to be working
```
kubectl get service
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP                                                               PORT(S)                                                       AGE
cadence                 LoadBalancer   172.20.55.119    a1d29011daeaa11ea86090ad68bc4645-927742592.us-west-2.elb.amazonaws.com    7933:31159/TCP,7934:31369/TCP,7935:32489/TCP,7939:31798/TCP   119s
```
I was able to create domain and start workflow. I can even see them queue up from the web UI
```
docker run --rm ubercadence/cli:master --address a1d29011daeaa11ea86090ad68bc4645-927742592.us-west-2.elb.amazonaws.com:7933 --do test-domain domain register -rd 1 
docker run --rm ubercadence/cli:master --address a1d29011daeaa11ea86090ad68bc4645-927742592.us-west-2.elb.amazonaws.com:7933 --do test-domain workflow start --tasklist HelloWorldTaskList --workflow_type HelloWorld::sayHello --execution_timeout 3600 --input \"World\"
```
But my Java worker cannot get the task and timeout. My worker code:
```Java
    public static void main(String[] args) {
        Worker.Factory factory = new Worker.Factory("a1d29011daeaa11ea86090ad68bc4645-927742592.us-west-2.elb.amazonaws.com", 7933, "test-domain");
        Worker worker = factory.newWorker("HelloWorldTaskList");
        worker.registerWorkflowImplementationTypes(HelloWorldImpl.class);
        factory.start();
    }
```
```
18:49:59.059 [Workflow Poller taskList="HelloWorldTaskList", domain="test-domain": 1] DEBUG com.uber.cadence.internal.worker.WorkflowWorker - poll request begin: PollForDecisionTaskRequest(domain:test-domain, taskList:TaskList(name:HelloWorldTaskList), identity:57759@gordons-mbp.lan)
18:49:59.066 [null: 1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
18:49:59.066 [null: 1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@6f93e75e
18:49:59.068 [null: 1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
18:49:59.069 [null: 1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
18:49:59.069 [null: 1] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
18:49:59.071 [null: 1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 32768
18:49:59.071 [null: 1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
18:49:59.071 [null: 1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
18:49:59.071 [null: 1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
18:49:59.096 [Workflow Poller taskList="HelloWorldTaskList", domain="test-domain": 1] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 57759 (auto-detected)
18:49:59.098 [Workflow Poller taskList="HelloWorldTaskList", domain="test-domain": 1] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
18:49:59.098 [Workflow Poller taskList="HelloWorldTaskList", domain="test-domain": 1] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
18:49:59.100 [Workflow Poller taskList="HelloWorldTaskList", domain="test-domain": 1] DEBUG io.netty.util.NetUtil - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1%lo0)
18:49:59.100 [Workflow Poller taskList="HelloWorldTaskList", domain="test-domain": 1] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
18:49:59.103 [Workflow Poller taskList="HelloWorldTaskList", domain="test-domain": 1] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: ac:de:48:ff:fe:00:11:22 (auto-detected)
18:52:00.197 [null: 1] WARN com.uber.cadence.internal.worker.Poller - Failure in thread null: 1
org.apache.thrift.transport.TTransportException: Request timeout after 121013ms
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.throwOnRpcError(WorkflowServiceTChannel.java:546)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.doRemoteCall(WorkflowServiceTChannel.java:519)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.pollForDecisionTask(WorkflowServiceTChannel.java:914)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.lambda$PollForDecisionTask$10(WorkflowServiceTChannel.java:902)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.measureRemoteCall(WorkflowServiceTChannel.java:569)
	at com.uber.cadence.serviceclient.WorkflowServiceTChannel.PollForDecisionTask(WorkflowServiceTChannel.java:901)
	at com.uber.cadence.internal.worker.WorkflowPollTask.poll(WorkflowPollTask.java:75)
	at com.uber.cadence.internal.worker.WorkflowPollTask.poll(WorkflowPollTask.java:35)
	at com.uber.cadence.internal.worker.Poller$PollExecutionTask.run(Poller.java:269)
	at com.uber.cadence.internal.worker.Poller$PollLoopTask.run(Poller.java:240)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sunshineo** [comment]
Sorry, it seems to me that it is working now. The messages get print out. But I just see this error frequently. Not sure if it matters

**Comment by sunshineo** [comment]
Sorry to re-open the issue. I do hope some expert can take a look to see if this is something we need to worry about.

**Comment by longquanzheng** [comment]
@sunshineo hey are you able to address the issue finally? it seems like some network issue between worker and server. 

Where do you run the CLI and worker? are they on the same local env?

**Comment by sunshineo** [comment]
Yeah, definitely was network issue.
